spring:
 datasource:
  url: jdbc:mysql://localhost:3306/etalon?characterEncoding=UTF-8
  username: root
  password: free
  driverClassName: com.mysql.jdbc.Driver
 jpa:
  hibernate.ddl-auto: update
  show-sql: false
